[package]
authors = ["Ricardo Martins <ricardo@scarybox.net>"]
description = "A µTP (Micro/uTorrent Transport Library) library implemented in Rust"
documentation = "http://meqif.github.io/rust-utp"
homepage = "https://github.com/maidsafe/rust-utp"
keywords = ["utp", "networking", "protocol", "transport"]
license = "MIT/Apache-2.0"
name = "temp_utp"
readme = "README.md"
repository = "https://github.com/meqif/rust-utp"
version = "0.6.3"

[dependencies]
env_logger = "0.3"
log = "0.3"
num = "0.1.27"
rand = "0.3"
time = "0.1.32"

[dev-dependencies]
quickcheck = "*"

[lib]
name = "utp"
